devices([
  "iPhone 17 Pro Max",
  "iPhone 17 Pro",
  "iPhone 16e"
])

languages(["en-US"])

scheme("Boxing TimerUITests")

output_directory("./fastlane/screenshots")

clear_previous_screenshots(true)

override_status_bar(true)

ios_version("26.3.1")
